name: Stefan-CI

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Code checkout
        uses: actions/checkout@v4
