name: Stefan-CI

on:
  - workflow_dispatch
  - push

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "21"
